about me + image + challenge 1 + challenge 2
DACSS/DACSS_601_August2022_v2 pull request #16
Opened 2022-08-17 22:02 UTC by miramanka

2022-08-17 23:14 UTC, mrolfe approved these changes
Looks great - thanks!

2022-08-17 23:33 UTC, ThogaruSathvik reviewed
Hi, Thanks for submitting in the new blog.
Your MirandaManka.qmd and the challenges are in the right folder.

Your image is in the wrong folder.
Delete your image in the images folder of project repository and add it in the about/images folder.

2022-08-18 00:00 UTC, ThogaruSathvik requested changes
Hi, Thanks for submitting in the new blog.
Your` MirandaManka.qmd` and the challenges are in the right folder.

Your image is in the wrong folder.
Delete your image in the` images `folder of project repository and add it in the` about/images` folder.

2022-08-18 13:46 UTC, maddiHz approved these changes

2022-08-18 15:53 UTC, ThogaruSathvik approved these changes

2022-08-19 02:37 UTC, merged