Challenge 2 - Lai Wei
DACSS/DACSS_601_August2022_v2 pull request #176
Opened 2022-08-26 22:14 UTC by laiwei1999

1st submission

2022-08-26 22:15 UTC, RosemaryPang approved these changes

2022-08-27 01:44 UTC, ThogaruSathvik requested changes
Can you please follow the instructions mentioned in the Slack by Meredith to resolve the conflicts and push your changes to your personal repo. 
https://2021summer601.slack.com/archives/C02FAJR857S/p1661532534619129

2022-08-27 15:19 UTC, laiwei1999 commented
> Can you please follow the instructions mentioned in the Slack by Meredith to resolve the conflicts and push your changes to your personal repo. https://2021summer601.slack.com/archives/C02FAJR857S/p1661532534619129

Hello, I put the commond in Terminal but it shows this, Did I operate correctly?
fatal: not a git repository (or any of the parent directories): .git
PS C:\Users\Lai Wei>

2022-08-28 19:20 UTC, ThogaruSathvik commented
> > Can you please follow the instructions mentioned in the Slack by Meredith to resolve the conflicts and push your changes to your personal repo. https://2021summer601.slack.com/archives/C02FAJR857S/p1661532534619129
> 
> Hello, I put the commond in Terminal but it shows this, Did I operate correctly? fatal: not a git repository (or any of the parent directories): .git PS C:\Users\Lai Wei>

Hi Lai Wei, the error means you attempted to run a Git command, but weren’t inside a Git repository. Run this command in the rstudio terminal of the DACSS 601 August 2022 v2 repo. If you face the same error we can connect tomorrow and resolve the issue. mean while you can work on the remoaning homework/challenges/project and save your work locally. Thank you

2022-08-29 15:56 UTC, merged