Homework submission
DACSS/DACSS_601_August2022_v2 pull request #75
Opened 2022-08-21 18:29 UTC by FrozenWolfyy

2022-08-21 20:09 UTC, ThogaruSathvik requested changes
Pavan can you remove the Instructions in the `about/pavanAbbineni.qmd` and resubmit agin.

2022-08-23 01:07 UTC, ThogaruSathvik approved these changes

2022-08-23 01:08 UTC, ThogaruSathvik requested changes
Can you submit it to Submission branch instead of template

2022-08-23 04:12 UTC, mrolfe commented
I'm going to close the pull request - please resubmit to the "submission" branch - not "template" branch (you can switch when you create a new pull request.

2022-08-23 04:12 UTC, closed without merging